cargo-features = ["edition2024"]

[package]
name = "tiny_os"
version = "0.1.0"
edition = "2024"
build = "build.rs"

[workspace]
members = [
  "macros"
]

[features]
default = []
test_run = []

[dependencies]
limine = "0.4"
x86_64 = "0.15.2"
os_macros = {path = "macros"}

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
