cargo-features = ["edition2024"]

[package]
name = "tiny_os"
version = "0.1.0"
edition = "2024"
build = "build.rs"

[features]
default = []
test_run = []

[dependencies]
limine = "0.4"
x86_64 = "0.15.2"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

# [package.metadata.bootimage]
# test-args = ["-device", "isa-debug-exit,iobase=0xf4,iosize=0x04", "-serial", "stdio", "-display", "none"]
# run-args = ["-device", "isa-debug-exit,iobase=0xf4,iosize=0x04"]
# test-success-exit-code = 33  
