[toolchain]
channel = "nightly"
targets = [
    "x86_64-unknown-none", #-uefi instead of none -> to use uefi-rs ?
    # "aarch64-unknown-none",
    # "riscv64gc-unknown-none-elf",
    # "loongarch64-unknown-none",
]
