name: test CI

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Install Rust Nightly
      run: rustup install nightly
      
    - name: Add Rust Components
      run: |
        cd ./kernel        
        rustup component add rust-src llvm-tools-preview

    - name: Install target
      run: rustup target add x86_64-unknown-none

    - name: Check Rust environment
      run: |
        rustup show
        rustup component list --installed
        cd ..

    - name: install deps
      run: |
        sudo apt-get update && sudo apt-get install -y qemu-system-x86 xorriso

    - name: Build test bin and run tests
      run: make test
